include $(GOROOT)/src/Make.inc

TARG=spectrum
GOFILES=\
	z80.go\
	z80_gen.go\
	z80_tables.go\
	opcodes_gen.go\
	memory.go\
	port.go\
	ula.go\
	display.go\
	sdldisplay.go\
	keyboard.go\
	spectrum.go\
	fpscounter.go\
	application.go

include $(GOROOT)/src/Make.pkg
