GOSPECCY_ROOT=../..
include $(GOSPECCY_ROOT)/Make.inc-head

TARG=spectrum/test
GOFILES=\
	test.go\

DEPS+="../prettytest" "../formats" "../spectrum" "../console"

include $(GOROOT)/src/Make.pkg
include $(GOSPECCY_ROOT)/Make.inc-tail
