// godefs -g perf types.c

// MACHINE GENERATED - DO NOT EDIT.

package perf

// Constants
const (
	SYS_PERF_OPEN = 0x150;
	TYPE_HARDWARE = 0;
	TYPE_SOFTWARE = 0x1;
	TYPE_TRACEPOINT = 0x2;
	TYPE_HW_CACHE = 0x3;
	TYPE_RAW = 0x4;
	TYPE_BREAKPOINT = 0x5;
	HW_CPU_CYCLES = 0;
	HW_INSTRUCTIONS = 0x1;
	HW_CACHE_REFERENCES = 0x2;
	HW_CACHE_MISSES = 0x3;
	HW_BRANCH_INSTRUCTIONS = 0x4;
	HW_BRANCH_MISSES = 0x5;
	HW_BUS_CYCLES = 0x6;
	HW_CACHE_L1D = 0;
	HW_CACHE_L1I = 0x1;
	HW_CACHE_LL = 0x2;
	HW_CACHE_DTLB = 0x3;
	HW_CACHE_ITLB = 0x4;
	HW_CACHE_BPU = 0x5;
	HW_CACHE_OP_READ = 0;
	HW_CACHE_OP_WRITE = 0x1;
	HW_CACHE_OP_PREFETCH = 0x2;
	HW_CACHE_RESULT_ACCESS = 0;
	HW_CACHE_RESULT_MISS = 0x1;
	SW_CPU_CLOCK = 0;
	SW_TASK_CLOCK = 0x1;
	SW_PAGE_FAULTS = 0x2;
	SW_CONTEXT_SWITCHES = 0x3;
	SW_CPU_MIGRATIONS = 0x4;
	SW_PAGE_FAULTS_MIN = 0x5;
	SW_PAGE_FAULTS_MAJ = 0x6;
	SW_ALIGNMENT_FAULTS = 0x7;
	SW_EMULATION_FAULTS = 0x8;
	ATTR_SIZE = 0x48;
	FLAG_DISABLED = 0x1;
	FLAG_INHERIT = 0x2;
	FLAG_PINNED = 0x4;
	FLAG_EXCLUSIVE = 0x8;
	FLAG_EXCLUDE_USER = 0x10;
	FLAG_EXCLUDE_KERNEL = 0x20;
	FLAG_EXCLUDE_HV = 0x40;
	FLAG_EXCLUDE_IDLE = 0x80;
	FLAG_MMAP = 0x100;
	FLAG_COMM = 0x200;
	FLAG_FREQ = 0x400;
	FLAG_INHERIT_STAT = 0x800;
	FLAG_ENABLE_ON_EXEC = 0x1000;
	FLAG_TASK = 0x2000;
	FLAG_WATERMARK = 0x4000;
)

// Types

type Attr struct {
	Type uint32;
	Size uint32;
	Config uint64;
	Sample_periodOrFreq uint64;
	Sample_type uint64;
	Read_format uint64;
	Flags uint64;
	Wakeup_eventsOrWatermark uint32;
	Bp_type uint32;
	Bp_addr uint64;
	Bp_len uint64;
}
