include $(GOROOT)/src/Make.$(GOARCH)

TARG=spectrum
GOFILES=\
	z80.go\
	memory.go\
	port.go\
	display.go\
	sdldisplay.go\
	keyboard.go\
	spectrum.go\
	filter.go\
	48.go

include $(GOROOT)/src/Make.pkg
